validations:
  user:
    password:
      minimum: 6
      maximum: 25
    email:
      minimum: 10
      maximum: 100
  work_space:
    name:
      minimum: 4
      maximum: 100
  todo:
    title:
      minimum: 4
      maximum: 100
enum:
  todo:
    status: ["TODO", "DOING", "DONE"]
    priority: ["LOW", "NORMAL", "HIGHT"]
pagination:
  default_per_page: 10
errors:
  something_went_wrong: SOMETHING_WENT_WRONG
  user:
    email_was_registered: EMAIL_WAS_REGISTERED
    email_not_registered: EMAIL_NOT_REGISTERED
    invalid_password: INVALID_PASSWORD
    not_authenticated: NOT_AUTHENTICATED
  work_space:
    work_space_not_found: WORK_SPACE_NOT_FOUND
  todo:
    not_found: TODO_NOT_FOUND
      
